language: python
python: 3.7
env: TRAVIS_NODE_VERSION=10
dist: xenial
sudo: true
branches:
  only:
    - master
install:
  - "pip install -U pip"
  - "pip install "werkzeug<1.0"
  - "pip install git+https://github.com/lektor/lektor#egg=Lektor"
  - "pip install "werkzeug<1.0"
script:
  - "lektor build"
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/lektor/builds
deploy:
  provider: script
  script: lektor deploy production
  on:
    branch: master
addons:
  ssh_known_hosts: flow.srv.pocoo.org

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f0c538cdfc9883f81e34
